name: Run Jest Tests For '02. 렌더링/02'

on:
  pull_request:
    branches: [main]
    paths:
      - '02. 렌더링/02/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Run Jest Tests
        run: npm test -- --coverage  --ci --reporters=default --reporters=jest-junit -- '02. 렌더링/02'

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: JEST Tests # Name of the check run which will be created
          path: junit.xml # Path to test results
          reporter: jest-junit # Format of test results
